# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_WORKSPACE: "{{flutter_app_1}}"
                XCODE_SCHEME: "{{Restaurant}}"
            xcode: latest
            cocoapods: default
        scripts:
            - flutter build ios --debug --no-codesign
